### ISSUE TITLE
Migration issues 0.21.0 to homebox:main branch

### ISSUE THREAD

**Issue by Saturo78** [sysadminsmedia/homebox#1107]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

:main

Hi,

I tested the `ghcr.io/sysadminsmedia/homebox:main` image and ran into issues when trying to migrate my existing Homebox database. I’m using **PostgreSQL**.

#### Steps I performed

1. I was previously running Homebox **0.21.0**.
2. I created a database dump using:

   ```bash
   docker exec -i homebox-db pg_dump -U *****-d *****> /home/.../homebox.sql
   ```
3. I imported this dump into a **fresh, empty PostgreSQL database**.
4. After starting the `homebox:main` container, Homebox enters a **startup loop** and fails due to migration errors.

#### Error details

I see repeated errors like:

```
invalid input syntax for type bigint: "true"
panic: ERROR 20250826000000_make_attachment_paths_relative.sql: failed to run SQL migration: 
failed to insert new goose version: pq: invalid input syntax for type bigint: "true"

goroutine 1 [running]:
main.main() /go/src/app/app/api/main.go:96 +0x6a
5:17PM ERR ../go/src/app/app/api/main.go:155 > failed to migrate database error="ERROR 20250826000000_make_attachment_paths_relative.sql: failed to run SQL migration: failed to insert new goose version: pq: invalid input syntax for type bigint: \"true\""
```

This repeats endlessly and prevents Homebox from starting.

#### Question

Is there a supported migration path from **0.21.0** to the current `main` branch?
Do I need to run any manual migration steps before importing my 0.21.0 dump, or is this an issue with the current `main` database migrations?

I’m really looking forward to the upcoming version with bulk actions, as I urgently need this feature.
However, I’m also concerned that the final update might run into similar migration issues, so I’d like to clarify the correct migration path in advance.

Any guidance would be greatly appreciated. Thanks!

---

### How can the maintainer reproduce the issue?

1. Start from a running Homebox **0.21.0** instance using PostgreSQL.
2. Create a dump of the database:

   ```bash
   docker exec -i <homebox-db-container> pg_dump -U **** -d **** > /home/.../homebox.sql
   ```
3. Create a **new, empty PostgreSQL database** and import the dump.
4. Deploy and start the container `ghcr.io/sysadminsmedia/homebox:main` pointing to this restored database.
5. Homebox will fail to start and continuously restart due to the Goose migration error shown above.

### Deployment

Docker (Linux)

### Database Type

PostgreSQL

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
Appears to be a Postgres issue with windows path fixing `\` escaping. I'll get a fix pushed up in a bit.

**Comment by tankerkiller125** [comment]
Please try again with main, I believe the image should have the fixed migration now.

**Comment by Saturo78** [comment]
Hi,
thanks for your answer and for updating the main image.

I just tested the migration again with a fresh database import from my 0.21.0 dump, but unfortunately I’m still seeing error messages on startup:

```
ERROR 20250826000000_make_attachment_paths_relative.sql: failed to run SQL migration: 
failed to insert new goose version: pq: invalid input syntax for type bigint: "true"
panic: ERROR 20250826000000_make_attachment_paths_relative.sql: failed to run SQL migration: 
failed to insert new goose version: pq: invalid input syntax for type bigint: "true"
```

This repeats in a loop and Homebox is unable to start.

**Comment by lhw** [comment]
I also noticed a migration error coming from 0.21.0. In my case its with sqlite3 and `20250907000000_make_password_nullable.sql` which is a sqlite3 specific error. I can't quite say why because the issue does not exist when i execute the SQL commands manually from said migration.

Here is the error log:
```log
homebox-1  | 8:42PM ERR ../go/src/app/app/api/main.go:155 > failed to migrate database error="ERROR 20250907000000_make_password_nullable.sql: failed to run SQL migration: failed to execute SQL query \"CREATE TABLE users_temp (\\n    id           uuid                not null\\n        primary key,\\n    created_at   datetime            not null,\\n    updated_at   datetime            not null,\\n    name         text                not null,\\n    email        text                not null,\\n    password     text,\\n    is_superuser bool default false  not null,\\n    superuser    bool default false  not null,\\n    role         text default 'user' not null,\\n    activated_on datetime,\\n    group_users  uuid                not null\\n        constraint users_groups_users\\n            references groups\\n            on delete cascade\\n);\\nINSERT INTO users_temp SELECT * FROM users;\\nDROP TABLE users;\\nALTER TABLE users_temp RENAME TO users;\\nCREATE UNIQUE INDEX users_email_key on users (email);\": SQL logic error: table users_temp has 11 columns but 13 values were supplied (1)"
homebox-1  | panic: ERROR 20250907000000_make_password_nullable.sql: failed to run SQL migration: failed to execute SQL query "CREATE TABLE users_temp (\n    id           uuid                not null\n        primary key,\n    created_at   datetime            not null,\n    updated_at   datetime            not null,\n    name         text                not null,\n    email        text                not null,\n    password     text,\n    is_superuser bool default false  not null,\n    superuser    bool default false  not null,\n    role         text default 'user' not null,\n    activated_on datetime,\n    group_users  uuid                not null\n        constraint users_groups_users\n            references groups\n            on delete cascade\n);\nINSERT INTO users_temp SELECT * FROM users;\nDROP TABLE users;\nALTER TABLE users_temp RENAME TO users;\nCREATE UNIQUE INDEX users_email_key on users (email);": SQL logic error: table users_temp has 11 columns but 13 values were supplied (1)
homebox-1  | 
homebox-1  | goroutine 1 [running]:
homebox-1  | main.main()
homebox-1  | 	/go/src/app/app/api/main.go:96 +0x6a
```

But if i execute it as follows it seems to work just fine:
```log
SQLite version 3.51.0 2025-06-12 13:14:41
Enter ".help" for usage hints.
sqlite> CREATE TABLE users_temp (
(x1...>     id           uuid                not null
(x1...>         primary key,
(x1...>     created_at   datetime            not null,
(x1...>     updated_at   datetime            not null,
(x1...>     name         text                not null,
(x1...>     email        text                not null,
(x1...>     password     text,
(x1...>     is_superuser bool default false  not null,
(x1...>     superuser    bool default false  not null,
(x1...>     role         text default 'user' not null,
(x1...>     activated_on datetime,
(x1...>     group_users  uuid                not null
(x1...>         constraint users_groups_users
(x1...>             references groups
(x1...>             on delete cascade
(x1...> );
sqlite> INSERT INTO users_temp SELECT * FROM users;
sqlite> DROP TABLE users;
sqlite> ALTER TABLE users_temp RENAME TO users;
sqlite> CREATE UNIQUE INDEX users_email_key on users (email);
sqlite> .schema
[...]
CREATE TABLE IF NOT EXISTS "users" (
    id           uuid                not null
        primary key,
    created_at   datetime            not null,
    updated_at   datetime            not null,
    name         text                not null,
    email        text                not null,
    password     text,
    is_superuser bool default false  not null,
    superuser    bool default false  not null,
    role         text default 'user' not null,
    activated_on datetime,
    group_users  uuid                not null
        constraint users_groups_users
            references groups
            on delete cascade
);
CREATE UNIQUE INDEX users_email_key on users (email);
```

**Comment by tankerkiller125** [comment]
I'm unable to replicate the SQLite issue, across multiple upgrade path (all the way back to hay-kots last version).

I haven't had a chance to dig deeper into Postgres yet, but hopefully tonight.

**Comment by tankerkiller125** [comment]
I'm unable to replicate this issue on Postgres, it seems that somehow you're `is_applied` column got changed to a `bitint` (I'm not sure how as we've never used the version of Goose that did that).

Running:
```sql
ALTER TABLE goose_db_version ALTER COLUMN is_applied type bool using is_applied::bool;
```

Should in theory fix it though.

**Comment by Saturo78** [comment]
Thanks for your tip regarding the is_applied column in goose_db_version. I had to create a temporary helper column to safely change the type, but following your suggestion, I was able to fix the issue. The database update now works correctly, and everything is running smoothly.

Really appreciate your help!

**Comment by lhw** [comment]
For completeness sake. I did the migration from 0.21.0 to 0.22.3 yesterday and did not run into the migration issue with sqlite3, so whatever changes were made between my comment and that released also fixed that issue. Thanks for taking a look at it, and yes the installation is quite old, pre-dating this repo by quite a bit.
