### ISSUE TITLE
The Chinese characters in the download tag cannot be displayed correctly

### ISSUE THREAD

**Issue by 389377616** [sysadminsmedia/homebox#1146]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.21.0 

### What is the issue you are experiencing?

The download tag shows Chinese characters in the image as □□□□

<img width="1600" height="739" alt="Image" src="https://github.com/user-attachments/assets/e91be80d-d6c4-4f80-9acd-ab8ab03bc870" />

<img width="526" height="200" alt="Image" src="https://github.com/user-attachments/assets/5018fa14-3d92-4040-983a-972237e317df" />

### How can the maintainer reproduce the issue?

Use the Chinese interface, and use Chinese characters for location names. You can see the problem by downloading the tags.

### Deployment

Docker (Linux)

### Database Type

SQLite

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
This was solved in #1038 and will be released in the next update.

**Comment by 389377616** [comment]
> This was solved in [#1038](https://github.com/sysadminsmedia/homebox/pull/1038) and will be released in the next update.

Did this update not fix this issue? My previous version number was v0.21.0, and today I saw a new update pushed out. I updated to version number v0.22.1, but the problem persists. Do I need to manually change any settings to resolve this issue?

**Comment by 389377616** [comment]
> This was solved in [#1038](https://github.com/sysadminsmedia/homebox/pull/1038) and will be released in the next update.

Solved. You need to use custom font variables in the environment variables:

HBOX_LABEL_MAKER_REGULAR_FONT_PATH

HBOX_LABEL_MAKER_BOLD_FONT_PATH

**Comment by 389377616** [comment]
I downloaded two fonts, NotoSansSC-Regular.ttf and NotoSansSC-Bold.ttf, and after setting the environment variables, I downloaded tags in Chinese. However, I found that the Chinese fonts don't seem to be complete. I don't know what the problem is.

<img width="540" height="390" alt="Image" src="https://github.com/user-attachments/assets/86e3feac-3bde-4718-9df2-dadc5203da45" />
