### ISSUE TITLE
Website (sysadminmedia.com) shows wrong link to homebox related things

### ISSUE THREAD

**Issue by s73ampunkca7** [sysadminsmedia/homebox#293]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

all

### What is the issue you are experiencing?

sysadminmedia.com links to homebox related things at homebox.sysadminmedia.com but the correct url should be homebox.software

### How can the maintainer reproduce the issue?

go to sysadminmedia.com and click on any homebox related link

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

**Comment by tankerkiller125** [comment]
Thanks for finding this, I've published a fix to the site.

**Comment by s73ampunkca7** [comment]
There is a link you missed:
![Image](https://github.com/user-attachments/assets/0348bafe-d286-48d8-a064-616b76a9be99)
 "[We released a roadmap for Homebox v1, check it out! »](https://homebox.sysadminsmedia.com/) < still links to the subdomain

**Comment by tankerkiller125** [comment]
Very strange, that should have been linking to the v1 roadmap blog post, I've fixed it though, so it should be working correctly now.
