### ISSUE TITLE
Long Title Goes Beyond Box

### ISSUE THREAD

**Issue by kangruixiang** [sysadminsmedia/homebox#355]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

Version: v0.15.2

### What is the issue you are experiencing?

Text wrap not correct with long titles:

![Image](https://github.com/user-attachments/assets/71e39ddf-01ef-4697-85aa-6efb1a2fc95e)

### How can the maintainer reproduce the issue?

This is the text to try:
Svarog 3Packs Motion Sensor Light Indoor, LED Closet Lights, Night Light Battery Powered, Battery Operated Under Cabinet Lights, Wireless Wall Puck Lamp Stick for Stair, Step, Hallway, Garage

### Deployment

Other

### OS Architechture

ARM64

### Deployment Details

I'm using HomeBox via Docker on Arc Browser on M1 Mac Mini.

**Comment by tankerkiller125** [comment]
Please clear the browser cache for your installation and try updating to v0.16.0. I've just validated on the Demo install that this is not an issue and was fixed in a prior PR.

![Image](https://github.com/user-attachments/assets/038b64b4-0648-4a5c-b279-adc6c7717f30)

**Comment by EdWorth120** [comment]
For me this is still an issue with Locations with long titles even in version 0.16.0, but the screen for assets was fixed in 0.15.2.
